version: "3.9"

services:
  db:
    image: postgres:16
    container_name: devconnect_db
    restart: always
    environment:
      POSTGRES_USER: devconnect
      POSTGRES_PASSWORD: devconnect
      POSTGRES_DB: devconnect
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - devconnect-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: devconnect_api
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/devconnect
      SPRING_DATASOURCE_USERNAME: devconnect
      SPRING_DATASOURCE_PASSWORD: devconnect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    networks:
      - devconnect-network

volumes:
  postgres_data:

networks:
  devconnect-network:
