name: Build and Test (Gradle)

on:
  push:
    branches: [main, develop, feature/*, task/*]
  pull_request:
    branches: [main, develop, feature/*, task/*]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Permitir execução do Gradle Wrapper
        run: chmod +x gradlew

      - name: Build do projeto
        run: ./gradlew build --no-daemon

      - name: Rodar testes
        run: ./gradlew test --no-daemon
